### ISSUE TITLE
Use pub-burrito for fork?

### ISSUE THREAD

**Issue by robertoandrade** [CloudCom/goose#11]
We've been keeping 3rd party forks under the [pub-burrito](https://github.com/pub-burrito) org instead of `CloudCom`, not sure if this is an exception to the rule?

**Comment by zabawaba99** [comment]
When I asked @guspinto about which organization to use for public facing Repos, he mentioned to use this one. Also, everything on `pub-burrito` is a fork from a GitHub repository (if I remember correctly?) but this one was moved from BitBucket

**Comment by phemmer** [comment]
I don't think whether a repo is forked or not should have any bearing on where the repo lives.
What is it we're really trying to accomplish here? That should be the question.
Are we trying to use pub-burrito for short lived repos that we're forking just to submit a PR? If so, this repo is not that. We have no intention of submitting changes back to the original project.

**Comment by robertoandrade** [comment]
traditionally we've been keeping public forks on `pub-burrito`. I don't think we have contributed any (or at least most) of the changes there. I think originally, as all repos in `CloudCom` were private, they didn't want to disclose the identity of that org publicly by having public forks there.

I'm fine either way to be honest, it's probably just a matter of organization in separating things that are core vs 3rd party forks. I have a few repos myself that I mirrored from googlecode and bitbucket in `pub-burrito` as well, so I agree with @phemmer that the origin shouldn't matter as where it lives. We now got 3 orgs (`CitrixConcierge`, `CloudCom` and `pub-burrito`) and just wanted to make sure we knew where to put what going forward :)

**Comment by Tonkpils** [comment]
Is there really a need for `pub-burrito` then?

**Comment by robertoandrade** [comment]
at this point there's some private repos in `CitrixConcierge` and some in `CloudCom` and there's a few public forks in `pub-burrito` and I think this one in `CloudCom`, so I guess we could either move all the `pub-burrito` ones to `CloudCom` (and get rid of that org) or move this one to `pub-burrito` and keep all 3 (one is more work than the other but I think it's all about what we think is the best way for us to manage our private and public org identities?)

**Comment by robertoandrade** [comment]
chatting with @guspinto he's of the opinion we can start using `CloudCom` for our public facing org on Github and get rid of `pub-burrito`.

I can start moving my forks from that org onto this org and change my build server and submodule references everywhere if everyone's in agreement?

PS: Not sure about the other repos in there if anyone needs them for anything current?

**Comment by zabawaba99** [comment]
I'm be completely fine with that @robertoandrade . I can take another glance at pub-burrito and see if there is anything we'd need from there.
