### ISSUE TITLE
Get rid of DBConf.PgSchema

### ISSUE THREAD

**Issue by phemmer** [CloudCom/goose#17]
The `OpenDBFromDBConf` function uses the `DBConf.PgSchema` variable to execute a command setting a postgres client connection parameter when first initializing the `sql.DB` object. This is a bad idea as the connection parameter is only applied for that specific connection. Golang's `sql.DB` driver transparently uses multiple connections, and there's a chance that you can get a new connection where that parameter has not been set.

If a consumer of this package wants to set a client connection parameter, they are welcome to set it within the transaction code.

**Comment by abourget** [comment]
Is there a way to ensure we're on the right schema then ? Can we limit the number of connections to a single one, and be sure we are on that schema ?  `goose` doesn't do much parallelization anyway

**Comment by phemmer** [comment]
You can just add a `SET search_path TO foo` at the top of your migrations that need it.
Even limiting connections to a single one isn't reliable, as the db driver can silently reconnect if the connection drops.
The documentation on the SQL driver has a little blurb about exactly this: http://golang.org/pkg/database/sql/#DB

> If the database has a concept of per-connection state, such state can only be reliably observed within a transaction
