### ISSUE TITLE
Who is the maintainer ?

### ISSUE THREAD

**Issue by abourget** [CloudCom/goose#20]
Are the folks at Cloud.com maintaining this project now ?  There are several interesting PRs back at bitbucket.org .. and Liam over there doesn't seem to be taking great care of the project.

I have things I'd like to improve.. but I'm still looking for the canonical location to which to contribute.  I'd be glad it's this place.. instead of trying to take it over.

**Comment by zabawaba99** [comment]
We forked the project from bitbucket because we wanted to make some modifications that we needed her at Cloud.com quickly. 

We are always open for improvements and plan on maintaining this project. If you'd like to contribute, feel free to open up some issues or pull requests!

**Comment by phemmer** [comment]
What he said :-)

We didn't create this repo with the intention of taking over the project. We just needed some changes made, and many of the changes were long outstanding issues on the upstream bug tracker, so we make it public so others can benefit.

We are happy to take pull requests, even if we (cloud.com) don't need them.
Issues submissions become another matter though. Bugs will likely be fixed fairly rapidly, but feature requests might collect dust. Though we can track them, and then take the pull request which implements them.
If our fork happens to be the one that everyone goes to, then great! If another fork ends up becoming actively maintained and more popular, then maybe we would drop this repo and start using it.

I think ultimately we'll just have to take it day by day and see what happens.
