### ISSUE TITLE
Ability to run all pending migrations (liamstask #38)

### ISSUE THREAD

**Issue by stilldavid** [CloudCom/goose#28]
Echoing the sentiments of [this issue](https://bitbucket.org/liamstask/goose/issues/38/ability-to-run-all-pending-migrations) on liamstack/goose on bitbucket.

I often get into this situation - is this something that is going to be addressed on this fork?

**Comment by phemmer** [comment]
Sounds like this would likely be easy to fix. I'll look into it in the next few days.
